name: client tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  client-tests:
    name: client-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run build
        working-directory: ./client
      - run: bun test
        working-directory: ./client