name: automated tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server-tests:
    name: server-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun test
  client-tests:
    name: client-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun test
      - run: bun run build
